<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>invoking_namespaces</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\branches-loops\branches-loops.csproj" />
    <ProjectReference Include="..\ConsoleApp1\ConsoleApp1.csproj" />
    <ProjectReference Include="..\ConsoleApp3\ConsoleApp3.csproj" />
    <ProjectReference Include="..\tubles\tubles.csproj" />
  </ItemGroup>

</Project>
